- name: Generate and Copy samba conf
  template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: "0644"
  become: yes

- name: Verify samba configuration
  command: testparm -s

- name: Make sure smbd Service is running
  systemd:
    state: started
    name: smbd
  become: yes

- name: Reload smbd Service
  systemd:
    state: reloaded
    name: smbd
  become: yes
